version: '3'

services: 
    redis:
        image: 'redis:latest'
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - '8080:80'
        depends_on:
            - api
            - client
    api:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/src/app/node_modules
            - ./server:/usr/src/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_USER=postgres
            - PG_PASSWORD=postgres_password
            - PG_DATABASE=postgres
        depends_on:
            - redis
            - postgres
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/src/app/node_modules
            - ./worker:/usr/src/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        stdin_open: true
        volumes: 
            - /usr/src/app/node_modules
            - ./client:/usr/src/app
